[build]
  publish = "."
  functions = ".netlify/functions"
  command = "cd .netlify/functions && npm install"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

# Explicitly disable all plugins
[plugins]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  port = 8888

[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "16" 