[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[dev]
  framework = "#static"
  targetPort = 3999
  port = 9000
  publish = "."
  autoLaunch = true
  command = "npm run dev"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
    [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.mp3"
    [headers.values]
    Content-Type = "audio/mpeg"

# Explicitly disable all plugins 