[build]
  functions = ".netlify/functions"
  publish = "."
  command = "npm install && cd .netlify/functions && npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  framework = "#static"
  functions = ".netlify/functions"
  publish = "."
  port = 8888

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8" 