[build]
  functions = ".netlify/functions"
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://avalonpd.netlify.app"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Content-Type = "application/json"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  framework = "#static"
  functions = ".netlify/functions"
  publish = "."
  port = 8888

[build.processing]
  skip_processing = true

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true" 