[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'No build command needed'"

[build.processing]
  skip_processing = true

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch", "fs", "path"]

[kv]
  chat = "chat_messages"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 